# ef-devnet-run — Local Devnet 引导脚本（writeShellApplication 脚本体）
# 首次启动生成私有链创世，此后直接复用；socket 统一暴露在 /run/echoforge/node.socket
#
# 为什么这里还要自己补配置和 Byron 创世：
#   cardano-cli conway genesis create-testnet-data 只产出创世与密钥
#   （shelley/alonzo/conway-genesis.json + delegate/pools/utxo keys），
#   它**不产出** cardano-node 的运行配置，也**不产出** Byron 创世。
#   而 cardano-node 的 `Protocol: Cardano` 强制要求 ByronGenesisFile
#   （缺了直接 `Missing required field, either ByronGenesisFile or GenesisFile`）。
#   配置则从发布件自带的 preview 配置派生（见下方），不手写。

STATE="${STATE_DIRECTORY:-/var/lib/echoforge/devnet}"
RUN_DIR="${RUNTIME_DIRECTORY:-/run/echoforge}"
MAGIC="${EF_DEVNET_MAGIC:-42}"
PORT="${EF_DEVNET_PORT:-6000}"
HOST="${EF_HOST:-127.0.0.1}"

GENESIS_DIR="$STATE/genesis"
CONFIG="$GENESIS_DIR/config.json"

# ── 出块与纪元参数：CLAUDE.MD §1 承诺的「秒级出块」在这里兑现 ──
# create-testnet-data 的内置默认是主网量级（f=0.05 → 约 20 秒一块，
# epochLength=432000 → 一个纪元 5 天），开发沙盒里跨不过任何纪元边界。
# 账本硬约束：epochLength >= 10 * securityParam / activeSlotsCoeff
#   k=36, f=0.5 → 下限 720。取 720：平均 2 秒出块，纪元 12 分钟。
DEV_K="${EF_DEVNET_K:-36}"
DEV_F="${EF_DEVNET_F:-0.5}"
DEV_EPOCH="${EF_DEVNET_EPOCH:-720}"

# 创世只在首次生成；之后改 echoforge.node.devnet.magic 不会自动重建 —— 从已有创世里读出真实 magic，把漂移说出来
if [ -f "$GENESIS_DIR/shelley-genesis.json" ]; then
  existing="$(sed -n 's/.*"networkMagic": *\([0-9][0-9]*\).*/\1/p' "$GENESIS_DIR/shelley-genesis.json" | head -n1)"
  if [ -n "$existing" ] && [ "$existing" != "$MAGIC" ]; then
    echo "!! existing devnet genesis uses magic $existing, configured $MAGIC" >&2
    echo "!! rm -rf $GENESIS_DIR (and /var/lib/echoforge/kupo) to regenerate" >&2
  fi
fi

# ── 什么时候需要重建创世 ──
# 1. 两份创世缺一：shelley（create-testnet-data 产出）或 byron（本脚本补齐）。
#    （旧版哨兵盯的是 configuration.yaml —— 那个文件谁都不会生成，于是每次启动
#      都 rm -rf 重建创世、然后节点找不到 config 崩溃重启。列上这两个还能让
#      装过旧版本、只剩半套创世的机器自动补全。）
# 2. 生成它的 cardano-cli 换了版本：创世的参数集合是跟版本走的，
#    比如 10.1.1 生成的 conway-genesis 只有 231 个参数，而 11.0.1 要 251 个，
#    直接报 "Number of parameters supplied 231 does not match the expected 251"。
#    不比对版本的话，每次升级 cardano-node 都会让 devnet 陷入永久崩溃重启。
VERSION_STAMP="$GENESIS_DIR/.ef-cardano-version"
current_version="$(cardano-cli --version | head -n1)"

regen=0
if [ ! -f "$GENESIS_DIR/shelley-genesis.json" ] || [ ! -f "$GENESIS_DIR/byron-genesis.json" ]; then
  regen=1
elif [ ! -f "$VERSION_STAMP" ] || [ "$(cat "$VERSION_STAMP")" != "$current_version" ]; then
  echo "!! devnet genesis was generated by [$(cat "$VERSION_STAMP" 2> /dev/null || echo unknown)]," >&2
  echo "!! now running [$current_version] — regenerating genesis and discarding the local chain" >&2
  regen=1
fi

if [ "$regen" = 1 ]; then
  # 创世换了，旧链数据库也就没意义了（Kupo 的索引同理，见 ef-cli node stop 的提示）
  rm -rf "$STATE/db"
  echo "==> First start: generating devnet genesis (magic=$MAGIC)"
  if [ "$MAGIC" = 20260411 ]; then echo "    2026-04-11 · founding day, written as a testnet magic"; fi
  rm -rf "$GENESIS_DIR"

  # --start-time 必须显式给「现在」：省略时 create-testnet-data 会把 systemStart
  # 放到未来 30 秒，节点要空等到那一刻才开 socket，首次启动凭空多 30 秒。
  # 另一头也不能回溯到 2026-04-11：KES / OpCert 的有效窗口从 systemStart 起算，回溯即过期。
  cardano-cli conway genesis create-testnet-data \
    --testnet-magic "$MAGIC" \
    --genesis-keys 1 \
    --pools 1 \
    --stake-delegators 1 \
    --utxo-keys 2 \
    --total-supply 45000000000000000 \
    --start-time "$(date -u +%Y-%m-%dT%H:%M:%SZ)" \
    --out-dir "$GENESIS_DIR"

  # 就地把主网量级的时序参数改成开发量级（密钥与分配不受影响）
  jq --argjson k "$DEV_K" --argjson f "$DEV_F" --argjson e "$DEV_EPOCH" \
    '.securityParam = $k | .activeSlotsCoeff = $f | .epochLength = $e' \
    "$GENESIS_DIR/shelley-genesis.json" > "$GENESIS_DIR/shelley-genesis.json.tmp"
  mv "$GENESIS_DIR/shelley-genesis.json.tmp" "$GENESIS_DIR/shelley-genesis.json"
  echo "    devnet timing: k=$DEV_K f=$DEV_F epochLength=$DEV_EPOCH (slot 1s)"

  # ── Byron 创世 ──
  # systemStart 必须与 shelley 完全同源，否则两个纪元的时钟不同步。
  byron_start="$(date -u -d "$(jq -r '.systemStart' "$GENESIS_DIR/shelley-genesis.json")" +%s)"
  cat > "$GENESIS_DIR/byron-pparams.json" <<'EOF'
{
  "heavyDelThd": "300000000000",
  "maxBlockSize": "2000000",
  "maxHeaderSize": "2000000",
  "maxProposalSize": "700",
  "maxTxSize": "4096",
  "mpcThd": "20000000000000",
  "scriptVersion": 0,
  "slotDuration": "1000",
  "softforkRule": {
    "initThd": "900000000000000",
    "minThd": "600000000000000",
    "thdDecrement": "50000000000000"
  },
  "txFeePolicy": {
    "multiplier": "43946000000",
    "summand": "155381000000000"
  },
  "unlockStakeEpoch": "18446744073709551615",
  "updateImplicit": "10000",
  "updateProposalThd": "100000000000000",
  "updateVoteThd": "1000000000000"
}
EOF
  cardano-cli byron genesis genesis \
    --genesis-output-dir "$GENESIS_DIR/byron" \
    --start-time "$byron_start" \
    --protocol-parameters-file "$GENESIS_DIR/byron-pparams.json" \
    --k "$DEV_K" \
    --protocol-magic "$MAGIC" \
    --n-poor-addresses 0 \
    --n-delegate-addresses 1 \
    --total-balance 1000000 \
    --delegate-share 1 \
    --avvm-entry-count 0 \
    --avvm-entry-balance 0
  cp "$GENESIS_DIR/byron/genesis.json" "$GENESIS_DIR/byron-genesis.json"

  # 版本戳最后写：中途失败就不会留下「和当前 cli 匹配」的假象，下次仍会重建
  echo "$current_version" > "$VERSION_STAMP"
fi

# ── 节点配置：每次启动按现有创世重新生成（幂等、可自愈）──
# 不手写配置，而是从发布件自带的 preview 配置派生：日志 / 追踪 / 共识那些
# 随版本演进的段落原样继承，升级时不会再出现「手写的旧格式解析不了」
# （11.0.1 换了新追踪系统，手写的旧 setupScribes 段直接报 key "Options" not found）。
# 只覆盖三件事：创世哈希、纪元从 0 起就在 Conway、去掉 preview 专属的检查点。
byron_hash="$(cardano-cli byron genesis print-genesis-hash --genesis-json "$GENESIS_DIR/byron-genesis.json")"
shelley_hash="$(cardano-cli conway genesis hash --genesis "$GENESIS_DIR/shelley-genesis.json")"
alonzo_hash="$(cardano-cli conway genesis hash --genesis "$GENESIS_DIR/alonzo-genesis.json")"
conway_hash="$(cardano-cli conway genesis hash --genesis "$GENESIS_DIR/conway-genesis.json")"

TEMPLATE="${EF_NODE_SHARE:?EF_NODE_SHARE not set (see modules/cardano/devnet.nix)}/preview/config.json"

jq \
  --arg by "$byron_hash" --arg sh "$shelley_hash" \
  --arg al "$alonzo_hash" --arg cw "$conway_hash" \
  '
    # CheckpointsFile 记的是 preview 真实链上的区块哈希，私有链必须去掉
    del(.CheckpointsFile, .CheckpointsFileHash)
    | .ByronGenesisHash   = $by
    | .ShelleyGenesisHash = $sh
    | .AlonzoGenesisHash  = $al
    | .ConwayGenesisHash  = $cw
    # 私有链从第 0 个纪元起就位于 Conway —— Aiken / Plutus V3 开箱可用
    | .TestShelleyHardForkAtEpoch = 0
    | .TestAllegraHardForkAtEpoch = 0
    | .TestMaryHardForkAtEpoch    = 0
    | .TestAlonzoHardForkAtEpoch  = 0
    | .TestBabbageHardForkAtEpoch = 0
    | .TestConwayHardForkAtEpoch  = 0
  ' "$TEMPLATE" > "$CONFIG"

# 单节点私有链：一个对端都不连。字段形状对齐发布件自带的 topology.json
# （11.x 多了 bootstrapPeers / trustable，publicRoots 也从裸数组变成对象数组）。
cat > "$STATE/topology.json" <<'EOF'
{
  "_comment": "bootstrapPeers: null = 显式关闭 bootstrap 模式。给空数组不行 —— 11.x 会报 'You seem to have not configured any trustable peers' 并退出。",
  "bootstrapPeers": null,
  "localRoots": [
    { "accessPoints": [], "advertise": false, "trustable": true, "valency": 1 }
  ],
  "publicRoots": [
    { "accessPoints": [], "advertise": false }
  ],
  "useLedgerAfterSlot": -1
}
EOF

# 供 Ogmios / Kupo 读取的统一节点配置入口。
# 注意：它们把配置里的相对创世路径按**软链自己所在的目录**解析（而不是软链目标的
# 目录），所以四份创世必须一并链进 $RUN_DIR，否则索引层启动即
#   Yaml file not found: /run/echoforge/byron-genesis.json
# cardano-node 本身不受影响 —— 它按命令行传入的真实 --config 路径解析。
ln -sf "$CONFIG" "$RUN_DIR/node-config.json"
for g in byron shelley alonzo conway; do
  ln -sf "$GENESIS_DIR/$g-genesis.json" "$RUN_DIR/$g-genesis.json"
done

echo "==> Starting devnet node on $HOST:$PORT (socket: $RUN_DIR/node.socket)"
exec cardano-node run \
  --config "$CONFIG" \
  --topology "$STATE/topology.json" \
  --database-path "$STATE/db" \
  --socket-path "$RUN_DIR/node.socket" \
  --shelley-kes-key "$GENESIS_DIR/pools-keys/pool1/kes.skey" \
  --shelley-vrf-key "$GENESIS_DIR/pools-keys/pool1/vrf.skey" \
  --shelley-operational-certificate "$GENESIS_DIR/pools-keys/pool1/opcert.cert" \
  --host-addr "$HOST" \
  --port "$PORT"
